version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=alexjmatos
      - POSTGRES_DB=masa_control
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=alexjmatos7@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=alexjmatos
    ports:
      - "81:80"
    depends_on:
      - postgres

